/* DO NOT EDIT!
   This file was automatically generated by m68k-palmos-multigen v2.3
   from ../resources/sied-dana.def  */

	.file	"sied-dana-sections.s"

	.globl	__text__
	.lcomm	__text__,4
	.globl	__text__utilfns
	.lcomm	__text__utilfns,4
	.globl	__text__filefns
	.lcomm	__text__filefns,4
	.globl	__text__diafns
	.lcomm	__text__diafns,4
	.globl	__text__texfns
	.lcomm	__text__texfns,4
	.globl	__text__editfns
	.lcomm	__text__editfns,4

.text
	.globl	_GccRelocateData
_GccRelocateData:
	bra.w	_GccLoadCodeAndRelocateData

.section ehook
	.long	_GccReleaseCode
